"use client";
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/layouts/Header";
import SubHeader from "@/layouts/SubHeader";
import ResponsiveHeader from "@/layouts/ResponsiveHeader";
import Footer from "@/layouts/Footer";
import { usePathname } from "next/navigation";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();

  // Hide Header on Admin Dashboard route
  const hideHeader = pathname.startsWith("/admin"); // adjust if your route is different
  const hideSubHeader = pathname.startsWith("/admin");

  // export default function RootLayout({
  //   children,
  // }: Readonly<{
  //   children: React.ReactNode;

  // }>) {
  return (
    <html lang="en">
      <body
      // className={${geistSans.variable} ${geistMono.variable} antialiased}
      >
        {!hideHeader && <Header />}
        {!hideSubHeader && <SubHeader />}
        <ResponsiveHeader />
        {children}
        <Footer />
      </body>
    </html>
  );
}
